using FrpManager.Models;
using System.Text;

namespace FrpManager.Helpers
{
    public static class ConfigHelper
    {
        // ── frpc.toml ─────────────────────────────────────────────────────
        public static string GenerateFrpcToml(
            ServerConfig s,
            IEnumerable<ProxyConfig> proxies,
            IEnumerable<VisitorConfig> visitors)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# frpc.toml — Generated by FrpManager");
            sb.AppendLine($"# {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine($"serverAddr = \"{s.ServerAddr}\"");
            sb.AppendLine($"serverPort = {s.ServerPort}");
            if (!string.IsNullOrWhiteSpace(s.NatHoleStunServer))
                sb.AppendLine($"natHoleStunServer = \"{s.NatHoleStunServer}\"");
            sb.AppendLine();

            if (s.AuthMethod != "none")
            {
                sb.AppendLine("[auth]");
                sb.AppendLine($"method = \"{s.AuthMethod}\"");
                if (s.AuthMethod == "token" && !string.IsNullOrWhiteSpace(s.Token))
                    sb.AppendLine($"token  = \"{s.Token}\"");
                sb.AppendLine();
            }

            sb.AppendLine("[log]");
            sb.AppendLine($"level = \"{s.LogLevel}\"");
            if (!string.IsNullOrWhiteSpace(s.LogFile))
                sb.AppendLine($"to    = \"{s.LogFile}\"");

            if (s.TlsEnable)
            {
                sb.AppendLine();
                sb.AppendLine("[transport.tls]");
                sb.AppendLine("enable = true");
            }

            // ── Proxies ───────────────────────────────────────────────────
            foreach (var p in proxies)
            {
                sb.AppendLine();
                sb.AppendLine("[[proxies]]");
                sb.AppendLine($"name      = \"{p.Name}\"");
                sb.AppendLine($"type      = \"{p.Type}\"");
                sb.AppendLine($"localIP   = \"{p.LocalIp}\"");
                sb.AppendLine($"localPort = {p.LocalPort}");

                switch (p.Type)
                {
                    case ProxyType.http:
                    case ProxyType.https:
                        if (!string.IsNullOrWhiteSpace(p.CustomDomains))
                            sb.AppendLine($"customDomains = [\"{p.CustomDomains}\"]");
                        if (!string.IsNullOrWhiteSpace(p.Subdomain))
                            sb.AppendLine($"subdomain = \"{p.Subdomain}\"");
                        break;
                    case ProxyType.stcp:
                    case ProxyType.xtcp:
                    case ProxyType.sudp:
                        if (!string.IsNullOrWhiteSpace(p.Sk))
                            sb.AppendLine($"secretKey = \"{p.Sk}\"");
                        break;
                    default:
                        sb.AppendLine($"remotePort = {p.RemotePort}");
                        break;
                }

                if (p.UseEncryption || p.UseCompression)
                {
                    sb.AppendLine("[proxies.transport]");
                    if (p.UseEncryption) sb.AppendLine("useEncryption  = true");
                    if (p.UseCompression) sb.AppendLine("useCompression = true");
                }
            }

            // ── Visitors ──────────────────────────────────────────────────
            foreach (var v in visitors)
            {
                sb.AppendLine();
                sb.AppendLine("[[visitors]]");
                sb.AppendLine($"name       = \"{v.Name}\"");
                sb.AppendLine($"type       = \"{v.Type}\"");
                sb.AppendLine($"serverName = \"{v.ServerName}\"");
                if (!string.IsNullOrWhiteSpace(v.ServerUser))
                    sb.AppendLine($"serverUser = \"{v.ServerUser}\"");
                if (!string.IsNullOrWhiteSpace(v.Sk))
                    sb.AppendLine($"secretKey  = \"{v.Sk}\"");
                sb.AppendLine($"bindAddr   = \"{v.BindAddr}\"");
                sb.AppendLine($"bindPort   = {v.BindPort}");

                // XTCP-only fields
                if (v.Type == ProxyType.xtcp)
                {
                    if (v.KeepTunnelOpen)
                        sb.AppendLine("keepTunnelOpen = true");
                    if (!string.IsNullOrWhiteSpace(v.FallbackTo))
                    {
                        sb.AppendLine($"fallbackTo        = \"{v.FallbackTo}\"");
                        sb.AppendLine($"fallbackTimeoutMs = {v.FallbackTimeoutMs}");
                    }
                }
            }

            return sb.ToString();
        }

        // ── frps.toml ─────────────────────────────────────────────────────
        public static string GenerateFrpsToml(ServerConfig s)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# frps.toml — Generated by FrpManager");
            sb.AppendLine($"# {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine($"bindPort = {s.ServerPort}");
            sb.AppendLine();
            if (s.AuthMethod != "none")
            {
                sb.AppendLine("[auth]");
                sb.AppendLine($"method = \"{s.AuthMethod}\"");
                if (s.AuthMethod == "token" && !string.IsNullOrWhiteSpace(s.Token))
                    sb.AppendLine($"token  = \"{s.Token}\"");
                sb.AppendLine();
            }
            sb.AppendLine("[webServer]");
            sb.AppendLine("addr = \"0.0.0.0\"");
            sb.AppendLine("port = 7500");
            if (s.TlsEnable)
            {
                sb.AppendLine();
                sb.AppendLine("[transport.tls]");
                sb.AppendLine("force = true");
            }
            return sb.ToString();
        }

        // ── Validation ────────────────────────────────────────────────────
        public static (bool Valid, List<string> Errors) Validate(
            ServerConfig s,
            IEnumerable<ProxyConfig> proxies,
            IEnumerable<VisitorConfig> visitors,
            string noMatchMsg = "No matching STCP/XTCP/SUDP proxy found")
        {
            var errs = new List<string>();
            var proxyList = proxies.ToList();
            var visitorList = visitors.ToList();

            if (string.IsNullOrWhiteSpace(s.ServerAddr))
                errs.Add("❌ Server address cannot be empty");
            if (s.ServerPort is <= 0 or > 65535)
                errs.Add($"❌ Server port invalid ({s.ServerPort}, must be 1-65535)");

            var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            int pi = 0;
            foreach (var p in proxyList)
            {
                pi++;
                string tag = string.IsNullOrWhiteSpace(p.Name) ? $"Proxy#{pi}" : $"Proxy[{p.Name}]";
                if (string.IsNullOrWhiteSpace(p.Name))
                    errs.Add($"❌ {tag} name cannot be empty");
                else if (!names.Add(p.Name))
                    errs.Add($"❌ Duplicate name: {p.Name}");

                if (p.LocalPort is <= 0 or > 65535)
                    errs.Add($"❌ {tag} local port invalid ({p.LocalPort})");

                switch (p.Type)
                {
                    case ProxyType.tcp:
                    case ProxyType.udp:
                        if (p.RemotePort is <= 0 or > 65535)
                            errs.Add($"❌ {tag} remote port invalid ({p.RemotePort})");
                        break;
                    case ProxyType.http:
                    case ProxyType.https:
                        if (string.IsNullOrWhiteSpace(p.CustomDomains) &&
                            string.IsNullOrWhiteSpace(p.Subdomain))
                            errs.Add($"❌ {tag} HTTP/HTTPS requires customDomains or subdomain");
                        break;
                }
            }

            int vi = 0;
            foreach (var v in visitorList)
            {
                vi++;
                string tag = string.IsNullOrWhiteSpace(v.Name) ? $"Visitor#{vi}" : $"Visitor[{v.Name}]";
                if (string.IsNullOrWhiteSpace(v.Name))
                    errs.Add($"❌ {tag} name cannot be empty");
                else if (!names.Add(v.Name))
                    errs.Add($"❌ Duplicate name: {v.Name}");

                if (string.IsNullOrWhiteSpace(v.ServerName))
                    errs.Add($"❌ {tag} serverName cannot be empty");

                // bindPort = -1 is valid for STCP fallback visitors
                if (v.BindPort != -1 && (v.BindPort is <= 0 or > 65535))
                    errs.Add($"❌ {tag} bindPort invalid ({v.BindPort})");

                if (string.IsNullOrWhiteSpace(v.BindAddr))
                    errs.Add($"❌ {tag} bindAddr cannot be empty");
            }

            return (errs.Count == 0, errs);
        }

        // ── Proxy Templates ───────────────────────────────────────────────
        public static ProxyConfig TcpTemplate() => new() { Name = "tcp-proxy", Type = ProxyType.tcp, LocalPort = 8080, RemotePort = 18080 };
        public static ProxyConfig SshTemplate() => new() { Name = "ssh", Type = ProxyType.tcp, LocalPort = 22, RemotePort = 6022 };
        public static ProxyConfig RdpTemplate() => new() { Name = "rdp", Type = ProxyType.tcp, LocalPort = 3389, RemotePort = 13389 };
        public static ProxyConfig WebTemplate() => new() { Name = "web", Type = ProxyType.http, LocalPort = 80, CustomDomains = "yourdomain.com" };
        public static ProxyConfig HttpsTemplate() => new() { Name = "web-https", Type = ProxyType.https, LocalPort = 443, CustomDomains = "yourdomain.com" };
        public static ProxyConfig UdpTemplate() => new() { Name = "udp-proxy", Type = ProxyType.udp, LocalPort = 5000, RemotePort = 15000 };
        public static ProxyConfig McTemplate() => new() { Name = "minecraft", Type = ProxyType.tcp, LocalPort = 25565, RemotePort = 25565 };
        public static ProxyConfig StcpTemplate() => new() { Name = "stcp-proxy", Type = ProxyType.stcp, LocalPort = 22, Sk = "your_secret" };
        public static ProxyConfig XtcpTemplate() => new() { Name = "xtcp-proxy", Type = ProxyType.xtcp, LocalPort = 22, Sk = "your_secret" };
        public static ProxyConfig SudpTemplate() => new() { Name = "sudp-proxy", Type = ProxyType.sudp, LocalPort = 5000, Sk = "your_secret" };

        // ── Visitor Templates ─────────────────────────────────────────────
        public static VisitorConfig StcpVisitorTemplate() => new()
        {
            Name = "stcp-visitor",
            Type = ProxyType.stcp,
            ServerName = "stcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 9000
        };

        public static VisitorConfig XtcpVisitorTemplate() => new()
        {
            Name = "xtcp-visitor",
            Type = ProxyType.xtcp,
            ServerName = "xtcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 6000
        };

        // STCP fallback visitor (bindPort = -1, only accepts fallback connections)
        public static VisitorConfig XtcpFallbackVisitorTemplate() => new()
        {
            Name = "stcp-fallback",
            Type = ProxyType.stcp,
            ServerName = "stcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = -1
        };

        // XTCP visitor with STCP fallback
        public static VisitorConfig XtcpWithFallbackTemplate() => new()
        {
            Name = "xtcp-visitor",
            Type = ProxyType.xtcp,
            ServerName = "xtcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 9002,
            FallbackTo = "stcp-fallback",
            FallbackTimeoutMs = 200
        };

        public static VisitorConfig SudpVisitorTemplate() => new()
        {
            Name = "sudp-visitor",
            Type = ProxyType.sudp,
            ServerName = "sudp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 6001
        };
    }
}