using FrpManager.Models;
using System.Text;

namespace FrpManager.Helpers
{
    /// <summary>
    /// Static helper class for generating, validating, and templating FRP TOML configurations.
    /// Provides methods to build frpc.toml and frps.toml content from application model objects,
    /// validate configuration completeness, and create commonly-used proxy/visitor templates.
    /// </summary>
    public static class ConfigHelper
    {
        // ── frpc.toml Generation ──────────────────────────────────────────────
        /// <summary>
        /// Generates the complete frpc.toml content from server config, proxy list, and visitor list.
        /// Items maintain their current collection order.
        /// </summary>
        /// <param name="s">Server connection configuration.</param>
        /// <param name="proxies">Collection of proxy rules. Keeps the incoming order.</param>
        /// <param name="visitors">Collection of visitor rules. Keeps the incoming order.</param>
        /// <returns>Full frpc.toml content as a string.</returns>
        public static string GenerateFrpcToml(
            ServerConfig s,
            IEnumerable<ProxyConfig> proxies,
            IEnumerable<VisitorConfig> visitors)
        {
            var sb = new StringBuilder();

            // ── Header comment with timestamp ──
            sb.AppendLine("# frpc.toml — Generated by FrpManager");
            sb.AppendLine($"# {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine($"serverAddr = \"{s.ServerAddr}\"");
            sb.AppendLine($"serverPort = {s.ServerPort}");
            if (!string.IsNullOrWhiteSpace(s.NatHoleStunServer))
                sb.AppendLine($"natHoleStunServer = \"{s.NatHoleStunServer}\"");
            sb.AppendLine();

            // ── Auth section (skip if none) ──
            if (s.AuthMethod != "none")
            {
                sb.AppendLine("[auth]");
                sb.AppendLine($"method = \"{s.AuthMethod}\"");
                if (s.AuthMethod == "token" && !string.IsNullOrWhiteSpace(s.Token))
                    sb.AppendLine($"token  = \"{s.Token}\"");
                sb.AppendLine();
            }

            // ── Log section ──
            sb.AppendLine("[log]");
            sb.AppendLine($"level = \"{s.LogLevel}\"");
            if (!string.IsNullOrWhiteSpace(s.LogFile))
                sb.AppendLine($"to    = \"{s.LogFile}\"");

            // ── TLS transport ──
            if (s.TlsEnable)
            {
                sb.AppendLine();
                sb.AppendLine("[transport.tls]");
                sb.AppendLine("enable = true");
            }

            // ── Proxies (maintained in their current order) ──
            foreach (var p in proxies)
            {
                sb.AppendLine();
                sb.AppendLine("[[proxies]]");
                sb.AppendLine($"name      = \"{p.Name}\"");
                sb.AppendLine($"type      = \"{p.Type}\"");
                sb.AppendLine($"localIP   = \"{p.LocalIp}\"");
                sb.AppendLine($"localPort = {p.LocalPort}");

                // Type-specific fields
                switch (p.Type)
                {
                    case ProxyType.http:
                    case ProxyType.https:
                        if (!string.IsNullOrWhiteSpace(p.CustomDomains))
                            sb.AppendLine($"customDomains = [\"{p.CustomDomains}\"]");
                        if (!string.IsNullOrWhiteSpace(p.Subdomain))
                            sb.AppendLine($"subdomain = \"{p.Subdomain}\"");
                        break;
                    case ProxyType.stcp:
                    case ProxyType.xtcp:
                    case ProxyType.sudp:
                        if (!string.IsNullOrWhiteSpace(p.Sk))
                            sb.AppendLine($"secretKey = \"{p.Sk}\"");
                        break;
                    default: // tcp, udp
                        sb.AppendLine($"remotePort = {p.RemotePort}");
                        break;
                }

                // ── Transport options (encryption / compression) ──
                if (p.UseEncryption || p.UseCompression)
                {
                    sb.AppendLine("[proxies.transport]");
                    if (p.UseEncryption) sb.AppendLine("useEncryption  = true");
                    if (p.UseCompression) sb.AppendLine("useCompression = true");
                }
            }

            // ── Visitors (maintained in their current order) ──
            foreach (var v in visitors)
            {
                sb.AppendLine();
                sb.AppendLine("[[visitors]]");
                sb.AppendLine($"name       = \"{v.Name}\"");
                sb.AppendLine($"type       = \"{v.Type}\"");
                sb.AppendLine($"serverName = \"{v.ServerName}\"");
                if (!string.IsNullOrWhiteSpace(v.ServerUser))
                    sb.AppendLine($"serverUser = \"{v.ServerUser}\"");
                if (!string.IsNullOrWhiteSpace(v.Sk))
                    sb.AppendLine($"secretKey  = \"{v.Sk}\"");
                sb.AppendLine($"bindAddr   = \"{v.BindAddr}\"");
                sb.AppendLine($"bindPort   = {v.BindPort}");

                // XTCP-only fields: keepTunnelOpen and STCP fallback
                if (v.Type == ProxyType.xtcp)
                {
                    if (v.KeepTunnelOpen)
                        sb.AppendLine("keepTunnelOpen = true");
                    if (!string.IsNullOrWhiteSpace(v.FallbackTo))
                    {
                        sb.AppendLine($"fallbackTo        = \"{v.FallbackTo}\"");
                        sb.AppendLine($"fallbackTimeoutMs = {v.FallbackTimeoutMs}");
                    }
                }
            }

            return sb.ToString();
        }

        // ── frps.toml Generation ─────────────────────────────────────────────
        /// <summary>
        /// Generates frps.toml (server-side config) from the server configuration.
        /// </summary>
        /// <param name="s">Server configuration.</param>
        /// <returns>Complete frps.toml content as a string.</returns>
        public static string GenerateFrpsToml(ServerConfig s)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# frps.toml — Generated by FrpManager");
            sb.AppendLine($"# {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine($"bindPort = {s.ServerPort}");
            sb.AppendLine();

            // ── Auth section ──
            if (s.AuthMethod != "none")
            {
                sb.AppendLine("[auth]");
                sb.AppendLine($"method = \"{s.AuthMethod}\"");
                if (s.AuthMethod == "token" && !string.IsNullOrWhiteSpace(s.Token))
                    sb.AppendLine($"token  = \"{s.Token}\"");
                sb.AppendLine();
            }

            // ── Web dashboard ──
            sb.AppendLine("[webServer]");
            sb.AppendLine("addr = \"0.0.0.0\"");
            sb.AppendLine("port = 7500");

            // ── TLS (force mode for server) ──
            if (s.TlsEnable)
            {
                sb.AppendLine();
                sb.AppendLine("[transport.tls]");
                sb.AppendLine("force = true");
            }
            return sb.ToString();
        }

        // ── Validation ───────────────────────────────────────────────────────
        /// <summary>
        /// Validates the server, proxy, and visitor configurations.
        /// Checks for empty names, duplicate names, invalid ports, missing domains,
        /// and missing serverName references for visitors.
        /// </summary>
        /// <param name="s">Server configuration to validate.</param>
        /// <param name="proxies">Proxy configurations.</param>
        /// <param name="visitors">Visitor configurations.</param>
        /// <param name="noMatchMsg">Message shown when a visitor references an unknown proxy.</param>
        /// <returns>A tuple: (valid, list of error messages).</returns>
        public static (bool Valid, List<string> Errors) Validate(
            ServerConfig s,
            IEnumerable<ProxyConfig> proxies,
            IEnumerable<VisitorConfig> visitors,
            string noMatchMsg = "No matching STCP/XTCP/SUDP proxy found")
        {
            var errs = new List<string>();
            var proxyList = proxies.ToList();
            var visitorList = visitors.ToList();

            // ── Validate server ──
            if (string.IsNullOrWhiteSpace(s.ServerAddr))
                errs.Add("❌ Server address cannot be empty");
            if (s.ServerPort is <= 0 or > 65535)
                errs.Add($"❌ Server port invalid ({s.ServerPort}, must be 1-65535)");

            // ── Validate proxies (with duplicate name detection) ──
            var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            int pi = 0;
            foreach (var p in proxyList)
            {
                pi++;
                string tag = string.IsNullOrWhiteSpace(p.Name) ? $"Proxy#{pi}" : $"Proxy[{p.Name}]";
                if (string.IsNullOrWhiteSpace(p.Name))
                    errs.Add($"❌ {tag} name cannot be empty");
                else if (!names.Add(p.Name))
                    errs.Add($"❌ Duplicate name: {p.Name}");

                // Local port validation (must be 1-65535)
                if (p.LocalPort is <= 0 or > 65535)
                    errs.Add($"❌ {tag} local port invalid ({p.LocalPort})");

                // Type-specific validation
                switch (p.Type)
                {
                    case ProxyType.tcp:
                    case ProxyType.udp:
                        if (p.RemotePort is <= 0 or > 65535)
                            errs.Add($"❌ {tag} remote port invalid ({p.RemotePort})");
                        break;
                    case ProxyType.http:
                    case ProxyType.https:
                        // HTTP/HTTPS must have either customDomains or subdomain
                        if (string.IsNullOrWhiteSpace(p.CustomDomains) &&
                            string.IsNullOrWhiteSpace(p.Subdomain))
                            errs.Add($"❌ {tag} HTTP/HTTPS requires customDomains or subdomain");
                        break;
                }
            }

            // ── Validate visitors (with duplicate name detection) ──
            int vi = 0;
            foreach (var v in visitorList)
            {
                vi++;
                string tag = string.IsNullOrWhiteSpace(v.Name) ? $"Visitor#{vi}" : $"Visitor[{v.Name}]";
                if (string.IsNullOrWhiteSpace(v.Name))
                    errs.Add($"❌ {tag} name cannot be empty");
                else if (!names.Add(v.Name))
                    errs.Add($"❌ Duplicate name: {v.Name}");

                // serverName is required for all visitors
                if (string.IsNullOrWhiteSpace(v.ServerName))
                    errs.Add($"❌ {tag} serverName cannot be empty");

                // bindPort = -1 is valid for STCP fallback visitors
                if (v.BindPort != -1 && (v.BindPort is <= 0 or > 65535))
                    errs.Add($"❌ {tag} bindPort invalid ({v.BindPort})");

                // bindAddr is required
                if (string.IsNullOrWhiteSpace(v.BindAddr))
                    errs.Add($"❌ {tag} bindAddr cannot be empty");
            }

            return (errs.Count == 0, errs);
        }

        // ── Proxy Templates ──────────────────────────────────────────────────
        // Each template provides sensible defaults for common use-cases.
        // Users can modify the created proxy in the editor after adding it.

        /// <summary>Generic TCP proxy template.</summary>
        public static ProxyConfig TcpTemplate() => new() { Name = "tcp-proxy", Type = ProxyType.tcp, LocalPort = 8080, RemotePort = 18080 };
        /// <summary>SSH tunnel template (port 22).</summary>
        public static ProxyConfig SshTemplate() => new() { Name = "ssh", Type = ProxyType.tcp, LocalPort = 22, RemotePort = 6022 };
        /// <summary>Remote Desktop (RDP) template.</summary>
        public static ProxyConfig RdpTemplate() => new() { Name = "rdp", Type = ProxyType.tcp, LocalPort = 3389, RemotePort = 13389 };
        /// <summary>HTTP web server template.</summary>
        public static ProxyConfig WebTemplate() => new() { Name = "web", Type = ProxyType.http, LocalPort = 80, CustomDomains = "yourdomain.com" };
        /// <summary>HTTPS web server template.</summary>
        public static ProxyConfig HttpsTemplate() => new() { Name = "web-https", Type = ProxyType.https, LocalPort = 443, CustomDomains = "yourdomain.com" };
        /// <summary>UDP proxy template.</summary>
        public static ProxyConfig UdpTemplate() => new() { Name = "udp-proxy", Type = ProxyType.udp, LocalPort = 5000, RemotePort = 15000 };
        /// <summary>Minecraft server template (TCP 25565).</summary>
        public static ProxyConfig McTemplate() => new() { Name = "minecraft", Type = ProxyType.tcp, LocalPort = 25565, RemotePort = 25565 };
        /// <summary>STCP (Secret TCP) proxy template.</summary>
        public static ProxyConfig StcpTemplate() => new() { Name = "stcp-proxy", Type = ProxyType.stcp, LocalPort = 22, Sk = "your_secret" };
        /// <summary>XTCP (P2P TCP) proxy template.</summary>
        public static ProxyConfig XtcpTemplate() => new() { Name = "xtcp-proxy", Type = ProxyType.xtcp, LocalPort = 22, Sk = "your_secret" };
        /// <summary>SUDP (Simple UDP) proxy template.</summary>
        public static ProxyConfig SudpTemplate() => new() { Name = "sudp-proxy", Type = ProxyType.sudp, LocalPort = 5000, Sk = "your_secret" };

        // ── Visitor Templates ────────────────────────────────────────────────
        // Visitors are the client-side counterparts for STCP/XTCP/SUDP proxies.
        // Each template corresponds to a matching proxy template above.

        /// <summary>STCP visitor template (standard).</summary>
        public static VisitorConfig StcpVisitorTemplate() => new()
        {
            Name = "stcp-visitor",
            Type = ProxyType.stcp,
            ServerName = "stcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 9000
        };

        /// <summary>XTCP visitor template (P2P with direct connection).</summary>
        public static VisitorConfig XtcpVisitorTemplate() => new()
        {
            Name = "xtcp-visitor",
            Type = ProxyType.xtcp,
            ServerName = "xtcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 6000
        };

        /// <summary>
        /// STCP fallback visitor template.
        /// bindPort = -1 means this visitor only accepts fallback connections,
        /// not direct connections from other clients.
        /// </summary>
        public static VisitorConfig XtcpFallbackVisitorTemplate() => new()
        {
            Name = "stcp-fallback",
            Type = ProxyType.stcp,
            ServerName = "stcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = -1
        };

        /// <summary>
        /// XTCP visitor with STCP fallback template.
        /// Attempts P2P hole-punching first; falls back to STCP relay if P2P fails.
        /// </summary>
        public static VisitorConfig XtcpWithFallbackTemplate() => new()
        {
            Name = "xtcp-visitor",
            Type = ProxyType.xtcp,
            ServerName = "xtcp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 9002,
            FallbackTo = "stcp-fallback",
            FallbackTimeoutMs = 200
        };

        /// <summary>SUDP visitor template.</summary>
        public static VisitorConfig SudpVisitorTemplate() => new()
        {
            Name = "sudp-visitor",
            Type = ProxyType.sudp,
            ServerName = "sudp-proxy",
            Sk = "your_secret",
            BindAddr = "127.0.0.1",
            BindPort = 6001
        };
    }
}
